language: elixir
elixir:
  - '1.8'

install:
  - cd doc
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - cd -

script:
  - cd doc
  - mix docs
  - cd -

deploy:
  provider: script
  script: bash doc/deploy-to-gh-pages.sh
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|release-[0-9]+\.[0-9]+)$
